defaults: &defaults
  adapter: <%= ENV['DB_ADAPTER'] || 'postgresql' %>
  encoding: <%= ENV['DB_ENCODING'] || 'utf8' %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  database: <%= ENV['POSTGRES_DB'] %>
  host: <%= ENV['DB_HOST']%>
  pool: 5

development:
  <<: *defaults
test:
  <<: *defaults
