defaults: &defaults
  adapter: <%= ENV['DB_ADAPTER'] || 'postgresql' %>
  encoding: <%= ENV['DB_ENCODING'] || 'utf8' %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  database: <%= ENV['POSTGRES_DB'] %>
  pool: 5

development:
  <<: *defaults
  host: <%= ENV['DB_HOST'] %>
#test:
#  <<: *defaults
#  host: db_test
